import express from 'express';
import authRoutes from './authRoutes.js';
import employeeRoutes from './employeeRoutes.js';
import attendanceRoutes from './attendanceRoutes.js';
import leaveRoutes from './leaveRoutes.js';
import payrollRoutes from './payrollRoutes.js';
import dashboardRoutes from './dashboardRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import faceRoutes from './faceRoutes.js';
import holidayRoutes from './holidayRoutes.js';
import ruleRoutes from './ruleRoutes.js';
import announcementRoutes from './announcementRoutes.js';
import feedbackRoutes from './feedbackRoutes.js';
import complaintRoutes from './complaintRoutes.js';
import performanceRoutes from './performanceRoutes.js';
import recruitmentRoutes from './recruitmentRoutes.js';
import departmentRoutes from './departmentRoutes.js';
import designationRoutes from './designationRoutes.js';
import leaveTypeRoutes from './leaveTypeRoutes.js';
const router = express.Router();

router.use('/auth', authRoutes);
router.use('/employees', employeeRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/leaves', leaveRoutes);
router.use('/payroll', payrollRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/notifications', notificationRoutes);
router.use('/face', faceRoutes);
router.use('/holidays', holidayRoutes);
router.use('/rules', ruleRoutes);
router.use('/announcements', announcementRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/complaints', complaintRoutes);
router.use('/performance', performanceRoutes);
router.use('/recruitment', recruitmentRoutes);
router.use('/departments', departmentRoutes);
router.use('/designations', designationRoutes);
router.use('/leave-types', leaveTypeRoutes);
export default router;
